services:
  database:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
  backend:
    image: sample
    ports: 
      - "3000:3000"
    restart: always
    environment:
      MONGODB_URL: mongodb://database:27017/${MONGODB_DATABASE}
    depends_on:
      - database
    links:
      - database
