name: Build
# on: 
#   workflow_run:
#     workflows: [Test]
#     types: 
#       - completed
on:
  workflow_run:
    workflows: [Test]
    types:
      - in_progress

jobs:
  something:
    runs-on: self-hosted
    steps:
      - run: echo Hello world