name: Build
on: 
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  build stuff:
    runs-on: self-hosted

    steps:
      - name: Print hello world
      run: echo Hello world