name: Deploy
on:
  push:
    branches:
      - '**'
jobs:
  delete-files-on-vm:
    runs-on: self-hosted
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Save ssh key
        run: echo "$DEPLOY_KEY" > ./key.pem
      - run: chmod 600 ./key.pem
      # - name: delete files
      #   run: ssh -i ./key.pem -T ec2-user@51.21.128.140 "rm -f ./*"
      
  
  build-and-copy-files-to-host:
    runs-on: self-hosted
    needs: delete-files-on-vm
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Installing node dependencies
        run: npm ci
      - name: Create docker tar from files
        run: npm run docker-tar
      - name: Save ssh key
        run: echo "$DEPLOY_KEY" > ./key.pem
      - run: chmod 600 ./key.pem
      - name: Send docker tar to server 
        # run: scp -i ./key.pem .env ./sample.tar ./compose.yaml ec2-user@51.21.128.140:.
        run: scp -i ./key.pem .env ec2-user@51.21.128.140:~/files

  stop-docker-containers:
    runs-on: self-hosted
    needs: build-and-copy-files-to-host
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Save ssh key
        run: echo "$DEPLOY_KEY" > ./key.pem
      - run: chmod 600 ./key.pem
      - name: stop docker containers
        run: ssh -i ./key.pem -T ec2-user@51.21.128.140 "docker stop $(docker ps -a -q)" || true
      - name: Docker rm application images
        run: ssh -i ./key.pem -T ec2-user@51.21.128.140 "docker rm sample" || true
