name: Deploy
on:
  workflow_run:
    workflows: ["Test"]
    # TODO: add branch: [main]

jobs:
  exit-if-tests-failed:
    runs-on: self-hosted
    if: github.event.Test.conclusion == 'success'
    steps:
      - run |
        echo something something
