name: test
on: [push]
jobs:
  linter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
        persist-credentials: false 
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint